name: CI workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run make setup
        run: make setup

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
